---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password-sdk-backend
spec:
  provider:
    onepasswordSDK:
      # MUST OVERRIDE
      vault: staging
      auth:
        serviceAccountSecretRef:
          name: onepassword-sa
          key: access-token

