---
apiVersion: v1
kind: Service
metadata:
 name: whoami
spec:
 ports:
   - name: web
     port: 80
     targetPort: web
   - name: webSecure
     port: 443
     targetPort: webSecure
 selector:
   app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: whoami
spec:
 selector:
   matchLabels:
     app: whoami
 template:
   metadata:
     labels:
       app: whoami
   spec:
     containers:
       - name: whoami
         image: traefik/whoami
         ports:
           - name: web
             containerPort: 80
           - name: webSecure
             containerPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: whoami
 annotations:
   cert-manager.io/issuer: "letsencrypt"
spec:
 tls:
   - hosts:
       - whoami.czifro.cloud
     secretName: tls-whoami-ingress-http
 rules:
   - host: whoami.czifro.cloud
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: whoami
               port:
                 name: web
