apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: czifro-cloud-cert
spec:
  secretName: czifro-cloud-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - czifro-cloud
  commonName: cert.czifro.cloud
  # MUST OVERRIDE
  dnsNames:
    - example.czifro.cloud
  issuerRef:
    name: czifro-cloud-le-issuer
    kind: Issuer
    group: cert-manager.io
