---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
spec:
  releaseName: external-secrets
  targetNamespace: default
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false
